# IBM training on Machine Learning

## firstly, please begin with "hello world"

In [103]:
print('Hello world')


Hello world


## then, try some complicate codes here:

In [104]:
from __future__ import print_function
import numpy as np
# import matplotlib
# matplotlib.use('agg')
import matplotlib.pyplot as plt

#import tensorflow as tf
#from tensorflow.contrib.timeseries.python.timeseries import NumpyReader

x = np.array(range(1000))
noise = np.random.uniform(-0.2, 0.2, 1000)
y = np.sin(np.pi * x / 100) + x / 200. + noise
plt.plot(x,y)
plt.show()
#plt.savefig('timeseries_y.jpg')

Above is a python code for generate a sin curve with random noise

## Let's learn some markdown label

**Bold text**: Enbrace with \**

*Italic text*: Enbrace with \*

***Bold and Italic text***: Enbrace with \***


**list**: start with +/-/* and a space before list item
- listitem1
- listitem2
   - item2.1
   + item2.2
   * item 2.3
- listitem 3   

**Quotation**: start with >
> **Behine every great fortune, there is a sin!**


**Table**

***简易版***

|姓名|技能|排行|
|--|:--:|--:|
|刘备|哭|大哥|
|关羽|打|二哥|
|张飞|骂|三弟|

直接按照HTML代码写：
<table width="70%">
   <tr>
       <th>姓名</th>
       <th>技能</th>
       <th>排行</th>
   </tr>
   <tr>
       <td>刘备</td>
       <td>哭</td>
       <td>大哥</td>
    </tr>
   <tr>
       <td>关羽</td>
       <td>打</td>
       <td>二哥</td>
    </tr>
   <tr>
       <td>张飞</td>
       <td>骂</td>
       <td>三弟</td>
    </tr>
</table>

**Code**
```
<javascript>
    sum=0;
    for(i=1;i<101;i++)
        sum+=i;
</javascript>
```


**Formule**

$$ f(x) = a\sqrt{x^3+bx^2+c} $$ 
$$ \hat{Y} = \frac1{1+e^{\beta_1(X-\beta_2)}} $$ 

$$
Probability =  P(Y=1|X) = 𝜎({θ^TX}) = \frac{e^{θ^TX}}{1+e^{θ^TX}} 
$$

# Let's come back to learning.

## Seahorse

The seahorse is an opensource tools. A machine training can be completed with a drag-and-drop manner, yes, just like AliCloud's max-computing. Here is the official website:
> <a href="https://seahorse.deepsense.ai/getting_started.html"> Seahorse's getting start! </a>

# Python basic

Python testing codes


In [105]:
A=('a','b','c')
print(A[0])

a


In [106]:
myList=['a']
myList.append(['c','b'])
myList

['a', ['c', 'b']]

Tuples (元组), List and Dictionary

In [107]:
list1=['Michael Jackson',10.5,2]
list1.append([1,2])
list1.extend([8])

print(list1[0].split(" "))

set1={1,1,2}
print(set1)



['Michael', 'Jackson']
{1, 2}


In [108]:
dic1={"key1":'Michael',"key2":"Chris"}

if 'key2' in dic1:
    print(dic1["key2"])
elif 'key3' in dic1:
    print(dic1["key3"])
else:
    print(dic1["key1"])
    
dic1['key3']='Wendy'
del(dic1['key3'])

dic1.keys()
dic1.values()


Chris


dict_values(['Michael', 'Chris'])

In [109]:
k=[1,2,3,4,5,6,7,8]
k

[1, 2, 3, 4, 5, 6, 7, 8]

In [110]:
k.index(5)

4

In [111]:
sorted(k)

[1, 2, 3, 4, 5, 6, 7, 8]

In [112]:
for i in range(0,6):
    s=''
    for j in range(0,i+1):
        s=s+'*'
    print(s)


*
**
***
****
*****
******


**How to use numpy**

In [132]:
import numpy as np

# present a vector
v=np.array([1,2,3])
v

# using range
y=np.array(range(3,10))
print(y)

# build a 3x3 matrix
A=np.array([[1,2,3],[2,3,4],[3,4,5]])
# build a 单位矩阵
UM=np.array([[1,0,0],[0,1,0],[0,0,1]])
A.dot(2*UM)

[3 4 5 6 7 8 9]


array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 6,  8, 10]])

In [126]:
# 对位相乘
a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])
print(a*b)
print(2*a)

[0 0 0 0 0]
[0 2 0 2 0]


In [116]:
# 矢量相乘/矩阵相乘
a=np.array([0,1])
b=np.array([1,0])

np.dot(a,b)

0